[app]
name = "bluebell"
port = 8080
mode = "release"

[snowflake]
start_time = 1577836800000
machine_id = 1

[log]
level = "info"
file_name = "/app/logs/bluebell.log"
max_size = 100
max_backups = 7
max_age = 30

[mysql]
host = "mysql"
port = 3306
passwd = "15939087780Ll@"
db_name = "bluebell"
user = "root"
max_open_conns = 200
max_idle_conns = 30

[redis]
host = "redis"
port = 6379
password = "bluebell_redis_password_secure"
db_name = 1
pool_size = 200

[rabbitmq]
url = "amqp://guest:guest@rabbitmq:5672/"

[ratelimit]
fill_interval = "10ms"
capacity = 200

[timeout]
timeout = "30s"

[jwt]
secret = "bluebell_prod_super_secret_jwt_key_2026_x9f7a2"
access_expiry = "120m"
refresh_expiry = "168h"
