target: all
multitenancy_enabled: false

server:
  http_listen_port: 9009
  grpc_listen_port: 9095

common:
  storage:
    backend: filesystem
    filesystem:
      dir: /var/mimir/data

blocks_storage:
  backend: filesystem
  filesystem:
    dir: /var/mimir/blocks
  bucket_store:
    sync_dir: /var/mimir/tsdb-sync

compactor:
  data_dir: /var/mimir/compact
  sharding_ring:
    kvstore:
      store: inmemory

ingester:
  ring:
    kvstore:
      store: inmemory
    replication_factor: 1
